### ISSUE TITLE
Updated readme fails to install

### ISSUE THREAD

**Issue by twpol** [russss/coviddata#3]
Commit 199abb23bc4cff4afb8099cebc7d114aef913e69 has updated the `README.md` file in such a way that the package no longer installs.

```
PS > python.exe --version
Python 3.8.2
PS > python.exe -c 'import sys; print(sys.getdefaultencoding())'
utf-8
PS > python.exe -m pip install --upgrade git+https://github.com/russss/coviddata@35ef347e16847b9c677f54336a891367e9f34cc9#egg=coviddata
Collecting coviddata from git+https://github.com/russss/coviddata@35ef347e16847b9c677f54336a891367e9f34cc9#egg=coviddata
  Cloning https://github.com/russss/coviddata (to revision 35ef347e16847b9c677f54336a891367e9f34cc9) to c:\users\james\appdata\local\temp\pip-install-bimr0827\coviddata
  Running command git clone -q https://github.com/russss/coviddata 'C:\Users\James\AppData\Local\Temp\pip-install-bimr0827\coviddata'
  Running command git checkout -q 35ef347e16847b9c677f54336a891367e9f34cc9
Requirement already satisfied, skipping upgrade: xarray in c:\python38\lib\site-packages (from coviddata) (0.15.1)
Requirement already satisfied, skipping upgrade: pandas in c:\python38\lib\site-packages (from coviddata) (1.0.3)
Requirement already satisfied, skipping upgrade: requests in c:\python38\lib\site-packages (from coviddata) (2.23.0)
Requirement already satisfied, skipping upgrade: lxml in c:\python38\lib\site-packages (from coviddata) (4.5.0)
Requirement already satisfied, skipping upgrade: html5lib in c:\python38\lib\site-packages (from coviddata) (1.0.1)
Requirement already satisfied, skipping upgrade: numpy>=1.15 in c:\python38\lib\site-packages (from xarray->coviddata) (1.18.3)
Requirement already satisfied, skipping upgrade: setuptools>=41.2 in c:\python38\lib\site-packages (from xarray->coviddata) (41.2.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.1 in c:\users\james\appdata\roaming\python\python38\site-packages (from pandas->coviddata) (2.8.1)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in c:\python38\lib\site-packages (from pandas->coviddata) (2019.3)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\python38\lib\site-packages (from requests->coviddata) (1.25.9)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in c:\python38\lib\site-packages (from requests->coviddata) (3.0.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\python38\lib\site-packages (from requests->coviddata) (2020.4.5.1)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in c:\python38\lib\site-packages (from requests->coviddata) (2.9)
Requirement already satisfied, skipping upgrade: six>=1.9 in c:\users\james\appdata\roaming\python\python38\site-packages (from html5lib->coviddata) (1.14.0)
Requirement already satisfied, skipping upgrade: webencodings in c:\users\james\appdata\roaming\python\python38\site-packages (from html5lib->coviddata) (0.5.1)
Installing collected packages: coviddata
  Found existing installation: coviddata 0.0.1
    Uninstalling coviddata-0.0.1:
      Successfully uninstalled coviddata-0.0.1
  Running setup.py install for coviddata ... done
Successfully installed coviddata-0.0.1
PS > python.exe -m pip install --upgrade git+https://github.com/russss/coviddata@199abb23bc4cff4afb8099cebc7d114aef913e69#egg=coviddata
Collecting coviddata from git+https://github.com/russss/coviddata@199abb23bc4cff4afb8099cebc7d114aef913e69#egg=coviddata
  Cloning https://github.com/russss/coviddata (to revision 199abb23bc4cff4afb8099cebc7d114aef913e69) to c:\users\james\appdata\local\temp\pip-install-0d6s412u\coviddata
  Running command git clone -q https://github.com/russss/coviddata 'C:\Users\James\AppData\Local\Temp\pip-install-0d6s412u\coviddata'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\James\\AppData\\Local\\Temp\\pip-install-0d6s412u\\coviddata\\setup.py'"'"'; __file__='"'"'C:\\Users\\James\\AppData\\Local\\Temp\\pip-install-0d6s412u\\coviddata\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\James\AppData\Local\Temp\pip-install-0d6s412u\coviddata\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\James\AppData\Local\Temp\pip-install-0d6s412u\coviddata\setup.py", line 4, in <module>
        long_description = fh.read()
      File "C:\Python38\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 190294: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

The readme also looks like a mess on GitHub, so it's possible something unintentional was done to it?

**Comment by russss** [comment]
Thanks, this was caused by the new xarray version which has pretty HTML rendering for jupyter notebooks. Apparently doesn't work very well with nbconvert (or indeed Github's notebook rendering).

I've removed that stuff from the README and linked it instead.
